// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Fred Hauschel

package de.hauschel.arknet.persistence;

/**
 * The absolute IRIs of arknet's PROV-O-based revision vocabulary as Java {@code String}
 * constants - the single source of truth shared by the code that <em>writes</em> revisions
 * (the {@link WriteFunnel}, which records one immutable revision plus the head rewrite
 * atomically with every guarded write, ADR-014) and any code that <em>reads</em> them
 * (head lookups, future change views).
 *
 * <p><strong>The shape of one revision record.</strong> Every write through the funnel adds,
 * inside the write transaction and only into {@link #PROVENANCE_GRAPH}:</p>
 *
 * <pre>
 * &lt;activity&gt; a prov:Activity .
 * &lt;revision&gt; a prov:Entity , arkprov:Revision ;
 *            prov:specializationOf &lt;resource&gt; ;
 *            prov:wasGeneratedBy   &lt;activity&gt; ;
 *            prov:generatedAtTime  "..."^^xsd:dateTime ;
 *            prov:wasRevisionOf    &lt;previous head, if any&gt; .
 * &lt;resource&gt; arkprov:head &lt;revision&gt; .
 * </pre>
 *
 * <p>The head triple is the resource's queryable pointer to its latest revision (ADR-014):
 * exactly one {@code arkprov:head} per resource, rewritten with every write <em>through the
 * funnel</em> - which today is every guarded write path. Where a caller reaches
 * {@link WriteFunnel#compareAndUpdate} the head is also a usable concurrency token; where it
 * reaches the unconditional {@link WriteFunnel#update} the head moves but guards nothing, and a
 * write issued directly against the store moves it not at all - see {@link WriteFunnel} for
 * both limits. The activity carries no resolved agent yet - agent attribution
 * ({@code prov:wasAssociatedWith}) is deliberately additive and out of scope here (ADR-014
 * decision 5).</p>
 *
 * <p><strong>A revision is not a snapshot.</strong> It records <em>that</em> a resource was
 * written, with its instant and its predecessor - the model graph itself is still replaced in
 * place, so no earlier state survives and two revisions cannot be compared against each other.
 * Making historical states queryable is open, and so is the compaction strategy the resulting
 * growth would need (both deferred by ADR-014). Nothing here is SHACL-validated either: the
 * gate runs on the candidate model graph before the transaction opens, while the revision is
 * written inside it into {@link #PROVENANCE_GRAPH}, for which arknet ships no shapes.</p>
 *
 * <p><strong>Why here.</strong> Like {@link ArkreqVocabulary} these are RDF serialization
 * constants, not domain vocabulary - the bounded-context cores never see them (opaque
 * identity), and as plain {@code String}s they keep this module RDF4J-free (ADR-007). The
 * ontology-side documentation of the same terms lives in
 * {@code arknet-ontology/src/main/resources/arknet-provenance.ttl}.</p>
 */
public final class ArkprovVocabulary {

    private static final String NAMESPACE = "https://w3id.org/arknet/provenance#";
    private static final String PROV_NAMESPACE = "http://www.w3.org/ns/prov#";

    /**
     * The named graph all revision records and head pointers live in - deliberately separate
     * from the bounded contexts' model graphs, so a replace-by-identity model write (which
     * deletes every subject triple in its own model graph) can never touch the revision trail.
     */
    public static final String PROVENANCE_GRAPH = "https://w3id.org/arknet/model/provenance";

    /**
     * Base IRI a revision's own identity is minted under - flat and opaque
     * ({@code REVISION_IRI_BASE + UUID}), deliberately separate from the resource-identity base
     * a bounded context mints under: a revision is infrastructure the funnel owns, not a model
     * resource. Shared between {@link WriteFunnel}, which mints revision identities under it,
     * and any read path that needs to recognise or shorten one for display (e.g. a
     * change-history read path) - the same "future change views" role the class javadoc names.
     */
    public static final String REVISION_IRI_BASE = "https://w3id.org/arknet/revision/";

    /** {@code arkprov:Revision} - the type of one immutable revision (a {@code prov:Entity}). */
    public static final String REVISION_TYPE = NAMESPACE + "Revision";

    /** {@code arkprov:head} - resource -&gt; its most recent revision written through the funnel. */
    public static final String HEAD = NAMESPACE + "head";

    /** {@code prov:Entity} - every revision is dually typed as a plain PROV entity. */
    public static final String ENTITY_TYPE = PROV_NAMESPACE + "Entity";

    /** {@code prov:Activity} - the write activity a revision was generated by. */
    public static final String ACTIVITY_TYPE = PROV_NAMESPACE + "Activity";

    /** {@code prov:wasGeneratedBy} - revision -&gt; the write activity. */
    public static final String WAS_GENERATED_BY = PROV_NAMESPACE + "wasGeneratedBy";

    /** {@code prov:generatedAtTime} - revision -&gt; its {@code xsd:dateTime} creation instant. */
    public static final String GENERATED_AT_TIME = PROV_NAMESPACE + "generatedAtTime";

    /** {@code prov:specializationOf} - revision -&gt; the evolving resource it is a state of. */
    public static final String SPECIALIZATION_OF = PROV_NAMESPACE + "specializationOf";

    /** {@code prov:wasRevisionOf} - revision -&gt; the head it superseded (absent on the first). */
    public static final String WAS_REVISION_OF = PROV_NAMESPACE + "wasRevisionOf";

    private ArkprovVocabulary() {
    }
}
