PREFIX arknet: <https://w3id.org/arknet/core#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT ?ctxUri ?term
WHERE {
  ?ctxUri a arknet:BoundedContext ;
          arknet:ubiquitousLanguageTerm ?concept .
  ?concept skos:prefLabel ?term .
}
ORDER BY ?ctxUri ?term
